gdown==5.2.0
  beautifulsoup4==4.12.3
    soupsieve==2.6
  filelock==3.16.1
  requests==2.32.3
    certifi==2024.8.30
    charset-normalizer==3.3.2
    idna==3.10
    urllib3==2.2.3
  tqdm==4.66.5
-e git+ssh://git@github.com/RunqiuYe/ls-iq.git@b097abd97f5e51c16d583bc9805cb40fb8e2ac01#egg=imitation_lib
  experiment-launcher==3.2
    GitPython==3.1.43
      gitdb==4.0.11
        smmap==5.0.1
    joblib==1.4.2
    numpy==1.26.4
    PyYAML==6.0.2
    wandb==0.18.1
      click==8.1.7
      docker-pycreds==0.4.0
        six==1.16.0
      GitPython==3.1.43
        gitdb==4.0.11
          smmap==5.0.1
      platformdirs==4.3.6
      protobuf==5.28.2
      psutil==6.0.0
      PyYAML==6.0.2
      requests==2.32.3
        certifi==2024.8.30
        charset-normalizer==3.3.2
        idna==3.10
        urllib3==2.2.3
      sentry-sdk==2.14.0
        certifi==2024.8.30
        urllib3==2.2.3
      setproctitle==1.3.3
      setuptools==75.1.0
  mushroom-rl==1.10.1
    joblib==1.4.2
    matplotlib==3.9.2
      contourpy==1.3.0
        numpy==1.26.4
      cycler==0.12.1
      fonttools==4.53.1
      kiwisolver==1.4.7
      numpy==1.26.4
      packaging==24.1
      pillow==10.4.0
      pyparsing==3.1.4
      python-dateutil==2.9.0.post0
        six==1.16.0
    numpy==1.26.4
    opencv-python==4.10.0.84
      numpy==1.26.4
      numpy==1.26.4
      numpy==1.26.4
      numpy==1.26.4
      numpy==1.26.4
      numpy==1.26.4
    pygame==2.6.0
    pytest==8.3.3
      iniconfig==2.0.0
      packaging==24.1
      pluggy==1.5.0
    scikit-learn==1.5.2
      joblib==1.4.2
      numpy==1.26.4
      scipy==1.14.1
        numpy==1.26.4
      threadpoolctl==3.5.0
    scipy==1.14.1
      numpy==1.26.4
    torch==2.2.2
      filelock==3.16.1
      fsspec==2024.9.0
      Jinja2==3.1.4
        MarkupSafe==2.1.5
      networkx==3.3
      sympy==1.13.3
        mpmath==1.3.0
      typing_extensions==4.12.2
    tqdm==4.66.5
  tensorboard==2.17.1
    absl-py==2.1.0
    grpcio==1.66.1
    Markdown==3.7
    numpy==1.26.4
    packaging==24.1
    protobuf==5.28.2
    setuptools==75.1.0
    six==1.16.0
    tensorboard-data-server==0.7.2
    Werkzeug==3.0.4
      MarkupSafe==2.1.5
-e git+ssh://git@github.com/RunqiuYe/loco-mujoco.git@3a0b152898612258a512fec79ffe119b92ba1aac#egg=loco_mujoco
  dm-control==1.0.14
    absl-py==2.1.0
    dm-env==1.6
      absl-py==2.1.0
      dm-tree==0.1.8
      numpy==1.26.4
    dm-tree==0.1.8
    glfw==2.7.0
    labmaze==1.0.6
      absl-py==2.1.0
      numpy==1.26.4
      setuptools==75.1.0
    lxml==5.3.0
    mujoco==2.3.7
      absl-py==2.1.0
      glfw==2.7.0
      numpy==1.26.4
      PyOpenGL==3.1.7
    numpy==1.26.4
    protobuf==5.28.2
    PyOpenGL==3.1.7
    pyparsing==3.1.4
    requests==2.32.3
      certifi==2024.8.30
      charset-normalizer==3.3.2
      idna==3.10
      urllib3==2.2.3
    scipy==1.14.1
      numpy==1.26.4
    setuptools==75.1.0
    tqdm==4.66.5
  GitPython==3.1.43
    gitdb==4.0.11
      smmap==5.0.1
  gymnasium==0.29.1
    cloudpickle==3.0.0
    Farama-Notifications==0.0.4
    numpy==1.26.4
    typing_extensions==4.12.2
  mujoco==2.3.7
    absl-py==2.1.0
    glfw==2.7.0
    numpy==1.26.4
    PyOpenGL==3.1.7
  mushroom-rl==1.10.1
    joblib==1.4.2
    matplotlib==3.9.2
      contourpy==1.3.0
        numpy==1.26.4
      cycler==0.12.1
      fonttools==4.53.1
      kiwisolver==1.4.7
      numpy==1.26.4
      packaging==24.1
      pillow==10.4.0
      pyparsing==3.1.4
      python-dateutil==2.9.0.post0
        six==1.16.0
    numpy==1.26.4
    opencv-python==4.10.0.84
      numpy==1.26.4
      numpy==1.26.4
      numpy==1.26.4
      numpy==1.26.4
      numpy==1.26.4
      numpy==1.26.4
    pygame==2.6.0
    pytest==8.3.3
      iniconfig==2.0.0
      packaging==24.1
      pluggy==1.5.0
    scikit-learn==1.5.2
      joblib==1.4.2
      numpy==1.26.4
      scipy==1.14.1
        numpy==1.26.4
      threadpoolctl==3.5.0
    scipy==1.14.1
      numpy==1.26.4
    torch==2.2.2
      filelock==3.16.1
      fsspec==2024.9.0
      Jinja2==3.1.4
        MarkupSafe==2.1.5
      networkx==3.3
      sympy==1.13.3
        mpmath==1.3.0
      typing_extensions==4.12.2
    tqdm==4.66.5
  numpy==1.26.4
  PyYAML==6.0.2
  scipy==1.14.1
    numpy==1.26.4
  wget==3.2
pipdeptree==2.23.4
  packaging==24.1
  pip @ file:///private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_0ato15bisz/croot/pip_1723484599651/work
pybind11 @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_3bs71k5pva/croot/pybind11-split_1712163757568/work
pybind11-global @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_3bs71k5pva/croot/pybind11-split_1712163757568/work
PySocks==1.7.1
wheel==0.44.0
